services:
  anime-downloader:
    build: .
    container_name: anime_unity_app
    ports:
      - "5050:5050"
    volumes:
      - ${FILM_PATH}:/app/Film/Downloads
      - ${SERIES_PATH}:/app/SerieTV/Downloads
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Rome
    restart: unless-stopped
